### ISSUE TITLE
Indexing ops should support unsigned integer types

### ISSUE THREAD

**Issue by AndrewZhaoLuo** [apache/tvm#10064]
Right now stuff like gather, take, gather_nd, scatter are bound to signed integers. This should be pretty simple to add, we just need to change the type relations to support, most of the topi should work out of box.

Portions of https://github.com/apache/tvm/pull/10053 apply insight into how to do this.

List of ops:
- [x] gather (@AndrewZhaoLuo)
- [x] gather_nd (@AndrewZhaoLuo)
- [x] take (@AndrewZhaoLuo)
- [x] scatter (@FZYUAN-1)
- [x] scatter_add (@FZYUAN-1)
- [x] scatter_nd (@FZYUAN-1)
- [x] unravel_index (@FZYUAN-1)
- [x] adv_index (@FZYUAN-1)

**Comment by FZYUAN-1** [comment]
Hello @AndrewZhaoLuo,

Can I take the last 5 ops (scatter, scatter_add, scatter_nd, unravel_index, adv_index)?

**Comment by AndrewZhaoLuo** [comment]
Yeah sure, thanks for the help B)
