### ISSUE TITLE
[Tracking Issue] Skip slow tests on PRs

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10132]
Tracking issue for work done on adding an `@slow` decorator to skip some tests in CI during pre-submit.

- [x] Merge RFC apache/tvm-rfcs#55
- [x] Add `@slow` decorator #10057
- [x] Investigate slow tests identified in https://discuss.tvm.apache.org/t/rfc-ci-skip-slow-tests-on-prs/11910

cc @mbrookhart  @driazati

**Comment by areusch** [comment]
Next steps:
- [ ] Re-generate the list of slow tests, since the long pole may have changed
- [ ] Triage those tests and determine if we can move any to post-merge build now via new `@slow` decorator.

**Comment by driazati** [comment]
the `@tvm.testing.slow` decorator is merged
