### ISSUE TITLE
[Tracking Issue] Add Hexagon CI docker image to pre-commit CI

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#10261]
We are adding a docker image to test hexagon tests in pre-commit CI. These are the steps:

- [x] Build ci-hexagon docker image locally and test it
- [x] Send a TVM PR with docker file and scripts to build ci-hexagon: https://github.com/apache/tvm/pull/10263
- [x] Add ci-hexagon to tlc-pack/tlcpack to rebuild: https://github.com/tlc-pack/tlcpack/pull/97
- [x] Confirm ci-hexagon rebuild nightly, pick a version that is green and push image to tlcpack/ci-hexagon:v0.01
- [x] Send TVM PR with JenkinsFile changes for ci-hexagon build/test: https://github.com/apache/tvm/pull/10302
- [x] Test this PR in tvm staging: https://ci.tlcpack.ai/job/tvm/job/ci-docker-staging/220/
- [x] Merge PR into main! This will add Hexagon docker to pre-commit CI

ci-hexagon has Hexagon SDK and we install other TVM dependencies such as python, LLVM, android SDK etc.

**Comment by mehrdadh** [comment]
retag image to hexagon-ci:v0.01

  ```bash
   docker pull tlcpackstaging/ci_hexagon:20220217-221509-47c23517f
   docker pull tlcpackstaging/ci_hexagon:20220217-221509-47c23517f tlcpack/ci-hexagon:v0.01
   docker push tlcpack/ci-hexagon:v0.01
 ```

**Comment by mehrdadh** [comment]
Image is published on tlcpack thanks to @areusch 
https://hub.docker.com/r/tlcpack/ci-hexagon/tags
