### ISSUE TITLE
[CI][Tracking Issue] @slow test tracking issue 

### ISSUE THREAD

**Issue by denise-k** [apache/tvm#10296]
### This issue is to track progress for the `@slow` decorator. 
- [x] Motivation for `@slow` decorator: https://github.com/apache/tvm-rfcs/pull/55
- [ ] Implementation of `@slow` decorator: https://github.com/apache/tvm/pull/10057 
- [ ] Analyze TVM's tests to find candidates for the `@slow` decorator
- [ ] Create an RFC sharing this analysis and proposing which tests to apply `@slow` to

cc @Mousius @areusch @driazati @gigiblender

**Comment by driazati** [comment]
The decorator is merged and users can add it as necessary, so closing this issue, though most test speedups now are from sharding / latency hiding
