### ISSUE TITLE
[Tracking Issue] Remove CODEOWNERS

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10575]
### This issue is to track progress for https://github.com/apache/tvm-rfcs/pull/58
- [x] Add `cc @<username>` people as reviewers #9934
- [x] Add workflow to ping users after period of no activity on PRs, still in opt-in phase #9973
- [x] Add workflow to cc teams tagged in PR titles #10322
- [x] Move CODEOWNERS file #10192
- [x] Add workflow to cc teams when tagged on PRs
- [x] ~~Add workflow to check required reviewers per-team and auto-add them to PRs tagged with that team~~
