### ISSUE TITLE
[Tracking Issue] Rebuild docker images on PRs

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10646]
This tracks https://discuss.tvm.apache.org/t/rfc-rebuild-docker-images-per-commit/12047

- [x] Rebuild docker images in PRs #10525
- [x] Upload built Docker images to a remote registry https://github.com/apache/tvm/pull/10662
- [ ] Detect new builds and use fresh Docker images in subsequent build steps on PRs #10664
- [ ] Push built Docker images from `main` to `tlcpack` when new images were built
- [ ] Switch Jenkinsfile to use `main-<hash>` tagged Docker images
- [ ] Document new update process
- [ ] Only rebuild edited images (see https://github.com/apache/tvm/pull/10525#discussion_r828522637)
