### ISSUE TITLE
[Tracking Issue] Enabling Testing in AArch64

### ISSUE THREAD

**Issue by Mousius** [apache/tvm#10673]
### This issue is to track progress enabling tests on AArch64
As part of enabling more tests in the AArch64 container, a number of tests had to be skipped and need to be fixed.

See also: https://github.com/apache/tvm/pull/10677 / https://github.com/apache/tvm/pull/10564

## Potential Schedule Issues

- [x]  [test_topi_conv2d_int8.py::verify_conv2d_NCHWc_int8](https://github.com/apache/tvm/blob/b01e3fc4d21bba898a5ea17d526013c52ea720eb/tests/python/topi/python/test_topi_conv2d_int8.py#L383-L392)
- [ ] test_op_level5.py::test_crop_and_resize

## xgboost issues
```
E           xgboost.core.XGBoostError: XGBoost Library (libxgboost.so) could not be loaded.
E           Likely causes:
E             * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
E             * You are running 32-bit Python on a 64-bit OS
E           Error message(s): ['/usr/local/lib/python3.7/dist-packages/xgboost/lib/../../xgboost.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block']
```
- [ ] test_model.py::test_tvmc_workflow
- [ ] tvmc/test_autoscheduler.py::test_tune_tasks
- [ ] tvmc/test_autoscheduler.py::test_tune_tasks__tuning_records
- [ ] tvmc/test_autoscheduler.py::test_tune_tasks__no_early_stopping
- [ ] tvmc/test_command_line.py::test_tvmc_cl_workflow
- [ ] tvmc/test_model.py::test_tvmc_workflow
- [ ] tvmc/test_frontends.py::test_load_model___wrong_language__to_pytorch

## Unsure
- [x] test_crt_aot.py::test_output_tensor_names

**Comment by masahi** [comment]
[test_topi_conv2d_int8.py::verify_conv2d_NCHWc_int8](https://github.com/apache/tvm/blob/b01e3fc4d21bba898a5ea17d526013c52ea720eb/tests/python/topi/python/test_topi_conv2d_int8.py#L383-L392) was fixed in https://github.com/apache/tvm/pull/10839

**Comment by leandron** [comment]
When enabling PyTorch and ONNX, I spotted a few more instance of these `libgomp` relates issues, so I'm adding new tests to the list of skipped tests in AArch64, for further investigation, but in the meanwhile, we guarantee that the other don't regress.

In the process of investigating these, I realised that no environment with torch is running integration tests (see https://github.com/apache/tvm/issues/12529), which is also reason for concern that should be fixed.

**Comment by leandron** [comment]
Just submitted https://github.com/apache/tvm/pull/12554 with the new tests that need skipping, now that I'm testing the environments *with* Torch installed.
