### ISSUE TITLE
[Tracking Issue] UMA: Universal Modular Accelerator Interface

### ISSUE THREAD

**Issue by MichaelJKlaiber** [apache/tvm#11260]
This is a global tracking issue for landing **UMA**. The original RFC can be found [here](https://github.com/boschresearch/tvm-rfcs/blob/rfc_uma/rfcs/00xx_UMA_Unified_Modular_Accelerator_Interface.md). Please feel free to bring in more questions to the corresponding thread.

To make the improvement manageable, we will be breaking the code into several steps. The main architecture scaffolding and
data structure changes will come first, then we will upstream individual key features.

# Steps

## [UMA-0] RFC 

- [x]  Definition of UMA-RFCv1  https://github.com/apache/tvm-rfcs/pull/60

## [UMA-1] Implementation of core infrastructure

  Implementation of `UMA Backend` according to UMA-RFCv1
  
  
  - [x] UMA Partitioner https://github.com/apache/tvm/pull/12087
  - [x] UMA Pipeline https://github.com/apache/tvm/pull/12087
  - [x] UMA Lower https://github.com/apache/tvm/pull/12087
  - [x] UMA Codegen https://github.com/apache/tvm/pull/12087
  - [x] Unit tests https://github.com/apache/tvm/pull/12087

## [UMA-2] Prototype of UMA using NN accelerator
 
 - [ ] Using UMA for deployment on **UltraTrail** NN accelerator (University of Tübingen, Germany)
 - [ ] Using UMA for deployment on NN accelerator_2 (to be defined)
 
## [UMA-3] Formulation of lessons learned for UMA_v1.0
 - [ ] Lessons learned and future topics document based on [UMA-2]
 - [ ] move OutlineCompilerFunctionsMutator out of UMA 
 - [ ] extend/add AOTTestRunner by project API 
 - [ ] annotations of UMALower._operator_strategies 
 - [ ] Add test case importing tflite model from .tflite file  https://github.com/apache/tvm/pull/12447
 - [ ] Add test case importing onnx model from .onnx file
  

## [UMA-4] Documentation 
 - [x] Vanilla Accelerator Tutorial https://github.com/apache/tvm/pull/12087
 - [ ] Strawberry Accelerator Tutorial
 - [ ] Chocolate Accelerator Tutorial

## [UMA-5] Suggestion from UMAv1 PR 
- [ ] Add UMA registration to tvmc
- [x] Case where we lower some parts with UMA while handling other unsupported parts via the conventional pipeline --> Integrate MobileNet unit test case https://github.com/apache/tvm/pull/12087
- [x] Tutorial as RST for gallery https://github.com/apache/tvm/pull/12087

# Backlog

- [ ] run BERT with UMA on ARM EthosU (No commitment by community yet)

# Working branch
https://github.com/MichaelJKlaiber/tvm/tree/uma

**Comment by gfvvz** [comment]
Hi, thanks for the work. Just want to know if there is a rough schedule on these features development?

**Comment by MichaelJKlaiber** [comment]
Hi @gfvvz , that's a great question. I'll try to come up with an answer asap. If you have input or feedback, feel free to reach out any time via Discord, GitHub or the TVM community forum

**Comment by areusch** [comment]
@gfvvz @MichaelJKlaiber FYI the tracking issue https://github.com/apache/tvm/issues/11260 should be the place we list that sort of thing

**Comment by cbalint13** [comment]
@MichaelJKlaiber ,

This is really great work, congratulations !

Watching with interest this ntiative, allow me to ask questions towards ***100% out-of-tree*** functionality.


#### Case usage:
----

 Given the case of a custom risc-v (or any llvm cpu) ISA extension (i.e. [custom HW/ISA](https://github.com/cbalint13/OLIMP) that itself can change&autotunne):

   * Currently (without UMA) it is necessary to **fork & insert** into TVM codebase:

       1. new strategies:
               ```python/tvm/relay/op/strategy/__init__.py```
               ```python/tvm/relay/op/strategy/olimp.py```

       2. new target:
	       ```python/tvm/target/__init__.py```
  	       ```python/tvm/target/target.py```

       3. some new topi that includes (auto)tensorization:
              ```python/tvm/topi/olimp/__init__.py```
              ```python/tvm/topi/olimp/conv2d.py```
              ```python/tvm/topi/olimp/dense.py```
              ```python/tvm/topi/olimp/injective.py```
              ```python/tvm/topi/olimp/tensor_intrin.py```
  
   Now after these **"C" code & binary libs** can be emmited that include **inline asm calls** with tensorized custom ISA.
   All **operators not covered** by declared **new strategies** defaults to **"the generic tvm"** not taking custom ISA advantage.

----

#### Now the questions: 

* Will UMA permit such workflow **without touching** and maintain a separate TVM fork / codebase ?
* [UMA RFC](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0060_UMA_Unified_Modular_Accelerator_Interface.md) tells to register a UMA (with nice class properties overrides) will all this be possible **100% out-of tree** ?

**Comment by MichaelJKlaiber** [comment]
@gfvvz , just added the link to our working branch, feel free to peek into (partially finished) functions.

**Comment by xinetzone** [comment]
`python/tvm/relay/backend/contrib/uma/backend.py` has a bug：

```python
for name, attr in self._target_attrs:
            if attr is None:
                raise ValueError("Target attribute None is not supported.")
```

can use:

```python
for attr in self._target_attrs.values():
            if attr is None:
                raise ValueError("Target attribute None is not supported.")
```

**Comment by areusch** [comment]
@xinetzone do you mind filing a separate issue and including some more detail (i.e. is there a stacktrace)?

**Comment by fabianpedd** [comment]
@xinetzone there is a PR for that already #12731

**Comment by areusch** [comment]
oh yes, thanks for the reminder @fabianpedd :)

**Comment by qzylalala** [comment]
Hi, thanks for the work.  Does this issue still active?
