### ISSUE TITLE
[RFC][Tracking Issue] CSI-NN2 Integration

### ISSUE THREAD

**Issue by alter-xp** [apache/tvm#11506]
### This issue to track upstreaming progress for CSI-NN2 integration.
[RFC] [RFC-CSI-NN2-Integration](https://github.com/apache/tvm-rfcs/pull/75)
- [x] P1. The CI environment support. https://github.com/apache/tvm/pull/11689
- [ ] P2. The backend with CSI-NN2 support and unit test for Conv2D.https://github.com/apache/tvm/pull/12526
- [ ] p3. More ops. Softmax, Pooling, Relu, and Dense.
