### ISSUE TITLE
Turn on IRModule mutation detector in tests by default

### ISSUE THREAD

**Issue by areusch** [apache/tvm#11551]
In #11372, @gigiblender created a utility that detects if an IRModule modifies any of the visitable attributes of an IRModule in-place. This issue tracks implementing that utility as the default in all Python tests. Here are the steps:

- [ ] Determine what kind of switch we should use for this. In the original PR, a switch was created using PassContext. We should find a way to modify the value of the switch for all tests via a pytest [fixture](https://docs.pytest.org/en/6.2.x/fixture.html).
- [ ] Add such pytest fixture to the codebase and determine which tests are failing, if any.
- [ ] Turn on the fixture for tests that aren't currently failing, and list the tests which need to be fixed here.
- [ ] Fix remaining tests as a community.

@mikepapadim is going to take a look at this.

**Comment by areusch** [comment]
i was thinking to do something kind of like this but rather put the variable in `tvm.testing` as a global var rather than environment var, and use [mock.patch](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) in a pytest fixture to set it. what do you think about that?
