### ISSUE TITLE
[Tracking Issue] Collage Partitioner

### ISSUE THREAD

**Issue by mbaret** [apache/tvm#11645]
This is a tracking issue for the Collage partitioner which is described in [RFC 62](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0062-collage.md).

Links to the pull requests will be added to the following items as they are upstreamed.
- [ ] Introduce the partitioning infrastructure with basic PartitionRules.
- [ ] Add further more complex PartitionRules.
- [ ] Introduce CostEstimators to estimate the cost of partitions.
- [ ] Introduce the CollagePartition pass which generates and estimates the cost of many different partitioning options and searches for the optimal partitioning using a Dijkstra-style algorithm.
