### ISSUE TITLE
[Tracking Issue] Refactor AOT executor codegen into IRModule -> IRModule form

### ISSUE THREAD

**Issue by mbaret** [apache/tvm#12548]
The AOT executor codegen has accumulated significant technical debt and dead code during its development, resulting in a component that is difficult to understand, test and extend. Refactoring it will improve code-quality and make it easier to introduce new features to expand the capabilities of AOT code generation.

This refactor aims to observe the following principles:
- Break the logic into passes with a single responsibility.
- Introduce tests for the internal logic of AOT (not just end-to-end integration testing).
- Remove side-channels and reduce the usage of 'magic attributes' to pass information.
- De-duplicate logic where possible.

### PRs
- [x] P1. Introduce a standalone pass to lower a Relay main to TIR https://github.com/apache/tvm/pull/12550
- [x] P2. Introduce an analysis pass to create the 'function metadata' https://github.com/apache/tvm/pull/13095
- [x] P3. Introduce an analysis pass to create the 'executor metadata' https://github.com/apache/tvm/pull/13250
- [ ] P4. Refactor AOTExecutorCodegenModule to use the new passes https://github.com/apache/tvm/pull/12549
- [ ] P5. Remove the 'StorageRewrite' memory planning strategy (USMP only)
- [ ] P?: Move context-specific passes out of the executor codegen (AnnotateUsedMemory/ConvertForLoopsToSerial)
- [ ] P?: Remove 'device_contexts' module attribute

**Comment by ekalda** [comment]
@areusch @mbaret is there a plan to continue this work? It looks like it's stuck in an awkward place where there is some duplicated code and a set of functions that are not used outside of the tests :)

**Comment by ekalda** [comment]
Yes, I don't think the efforts to prototype Relax should justify bringing technical dept into TVM, so it would be better to remove the duplicated code. I don't think it is blocking anybody though, so it's not urgent.
