### ISSUE TITLE
[Tracking Issue] Issue Triage RFC

### ISSUE THREAD

**Issue by areusch** [apache/tvm#12801]
### This issue is to track progress for [Issue Triage RFC](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0093_Issue_Triage.md). This issue has these tasks:

- [ ] Create labels described in the RFC.
- [ ] Modify ISSUE_TEMPLATES to remove Update CI Docker Image issue template and add `needs-triage` label. https://github.com/apache/tvm/pull/12898
- [ ] Mark all existing issues needs-triage
- [ ] Manually re-triage all issues in the codebase.
- [ ] Add `triage-bot` with unit test and allow for use on labels created by a small set of beta-test users.
- [ ] Expand `triage-bot` to everyone.

cc @hpanda-naut

**Comment by hpanda-naut** [comment]
### This issue is to track progress for [Issue Triage RFC](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0093_Issue_Triage.md). This issue has these tasks:
 * [x]  Create labels described in the RFC.
 * [ ]  Modify ISSUE_TEMPLATES to remove Update CI Docker Image issue template and add `needs-triage` label. [[skip ci] Modify issue templates to align with Issue Tracking RFC #12898](https://github.com/apache/tvm/pull/12898)
 * [ ]  Mark all existing issues needs-triage
 * [ ]  Manually re-triage all issues in the codebase.
 * [ ]  Add `triage-bot` with unit test and allow for use on labels created by a small set of beta-test users.
 * [ ]  Expand `triage-bot` to everyone.

cc @areusch
