### ISSUE TITLE
[Tracking Issue] TVM Explorer Infrastructure

### ISSUE THREAD

**Issue by chunit-quic** [apache/tvm#13116]
### This issue is to track progress for [TVM Explorer Infrastructure](https://discuss.tvm.apache.org/t/pre-rfc-tvm-explorer-infrastructure/13457).

Main authors: @chunit-quic, @haowhsu-quic, @zack-ch  
RFC: [link](https://github.com/apache/tvm-rfcs/pull/92#issuecomment-1281411754)
# A. Span filling for frontends to Relay
- [x] Common API
- [x] TensorFlow 1
- [x] TFLite
- [x] PyTorch
- [x] ONNX

# B. Schedule/Stage visualization enhancement
- [x] Schedule record and API changes
- [x] TEDD modification

# C. Span propagation of Relay passes (passes within regular build flow will be covered)
- [ ] SequentialSpan and Source information builder
- [ ] Series of passes

Note that the span propagation of TIR passes is working in progress and not specifically included here. We are still refining some strategies to deal with span propagation from Relay and testing infrastructure. Beside, based on the discussion in pre-RFC about the tracing map, it might also affect the span filling design in the future.
