### ISSUE TITLE
[Tracking Issue] Rust Embedded API

### ISSUE THREAD

**Issue by Mousius** [apache/tvm#13705]
### This issue is to track progress for Rust Embedded API
- [ ] P1. Add Rust name transforms - https://github.com/apache/tvm/pull/13706
- [ ] P2. Add Rust interface generator - https://github.com/apache/tvm/pull/13707
- [ ] P3. Initial Rust MLF generation and testing
- [ ] P4. Add Rust Traits Crate
- [ ] P5. Rust Crate MLF generation
- [ ] P6. Rust API alignment with RFC
- [ ] P7. Rust Device API
