### ISSUE TITLE
[RFC][Tracking Issue] Introduce PresburgerSet

### ISSUE THREAD

**Issue by multiverstack-intellif** [apache/tvm#14006]
### This issue is to track progress for RFC#99: [Introduce PresburgerSet](https://github.com/apache/tvm-rfcs/pull/99)
- [ ] P1. Build & CI setup, PresburgerSet class with minimal member functions.
- [ ] P2. Basic set manipulation functions.
- [ ] P3. Dependency analysis utilities.
- [ ] P4. Helper functions for block analysis.

**Comment by p3achyjr** [comment]
Hello--is this work still in progress, and would you be open to contributions?
