### ISSUE TITLE
[Unity][Tracking Issue] CoreML BYOC

### ISSUE THREAD

**Issue by sunggg** [apache/tvm#15245]
### This issue is to track progress for Unity CoreML
- [x] P1. `PrimValue` support in `FuseOpsByPattern`: https://github.com/apache/tvm/pull/15217
- [x] P2. Handle `R.output` with `CanonicalizeBindings`: https://github.com/apache/tvm/pull/15341
- [x] P3. Match behavior between `FuseOpsByPattern(..., annotate_codegen=True)` and `MergeCompositeFunctions()`: https://github.com/apache/tvm/pull/15491
- [ ] P4. CoreML codegen and runtime: https://github.com/apache/tvm/pull/15556
- [ ] P5. Performance debugging

cc. @tqchen 

cc @quic-sanirudh
