### ISSUE TITLE
[Release] v0.14.0 release schedule

### ISSUE THREAD

**Issue by ysh329** [apache/tvm#15812]
> [Last release v0.13.0](https://github.com/apache/tvm/releases/tag/v0.13.0) is on 14 July and the branch cut day is 1 July [v0.13.0 release schedule](https://github.com/apache/tvm/issues/15134). It has been almost **three months** since 1 July. According to our [RFC-0067 about quarter-based releases](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md), I **hope to release v0.14.0 version in mid Oct**. It's meaningful especially for **AI infra companies which needs regularly merge with release version.**
**In order to continue with our agreed release cycle as per discussion in [RFC#67](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md) , I'd like to propose a schedule for our next TVM release: `v0.14.0`.**

This schedule is tentative and may change as we progress through the process. In case dates change, this thread will be kept updated.

The proposed schedule is:

- [x] **16 Oct 2023** Following three actions should be continuous and coherent:
  - [x] Make version modification twice as two commits: first to `v0.14.0` on main branch; second to `v0.15.dev0` on main branch in one PR, and **merged without squash (required)**. Why do this first [referring discuss on last release](https://github.com/apache/tvm/issues/15134#issuecomment-1607649151):
      - [x] https://github.com/apache/tvm/pull/15847
      - [x] https://github.com/apache/tvm/pull/15934
  - [x] A branch `v0.14.0` to be created from `main` on first commit: https://github.com/apache/tvm/tree/v0.14.0;
  - [x] A tag named `v0.14.0.rc0` created on first commit: https://github.com/apache/tvm/releases/tag/v0.14.0.rc0
  - [x] A tag named `v0.15.dev0` created on second commit: https://github.com/apache/tvm/releases/tag/v0.15.dev0
- [x] **19 Oct 2023** - Cherry-picking soft deadline
  - During this time any reasonable change can be merged, comment on this issue with the commit you would like added to the release branch
- [x] **22 Oct 2023** - Cherry-picking **hard deadline**
  - During this time only critical changes will be merged, comment on this issue with the commit you would like added to the release branch as well as the reasoning for adding it
- [x] **23 Oct 2023** - Draft release notes published, https://github.com/apache/tvm/issues/15948
- [x] **23 Oct 2023** - [Prepare release candidate packaging `v0.14.0.rc0` and uploading](https://tvm.apache.org/docs/contribute/release_process.html#upload-the-release-candidate)
  - Create tag `v0.14.0.rc0` and Github release page: https://github.com/apache/tvm/releases/tag/v0.14.0.rc0
  - Upload to Apache repo: https://dist.apache.org/repos/dist/dev/tvm/tvm-v0.14.0-rc0/
- [x] **24 Oct 2023** - Release voting opens, https://github.com/apache/tvm/issues/15974
- [x] **30 Oct 2023**
  - [x] Voting result, https://github.com/apache/tvm/issues/16022
  - [x] Create a new release tag `v0.14.0` on last commit on release branch: https://github.com/apache/tvm/releases/tag/v0.14.0
  - [x] Upload the binaries to Apache mirrors: https://dist.apache.org/repos/dist/release/tvm/tvm-v0.14.0/
- [x] **31 Oct 2023** - Release date
- [x] **31 Oct 2023** - Update the TVM Website: https://tvm.apache.org/docs/v0.14.0/

**Call for release managers:** In case you want to be involved in upcoming releases, please manifest your interest in this thread and we'll try to organise. 😆

See also:

- [Release steps](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md#reference-level-explanation)
- [TVM release process docs](https://tvm.apache.org/docs/contribute/release_process.html).

cc @apache/tvm-committers [@Hzfengsy](https://github.com/Hzfengsy) [@vinx13](https://github.com/vinx13)  [@areusch](https://github.com/areusch) [@Mousius](https://github.com/Mousius) [@tqchen](https://github.com/tqchen) [@AndrewZhaoLuo](https://github.com/AndrewZhaoLuo)

**Comment by ysh329** [comment]
Here, let me explan why first version modification to `v0.14.0` on main branch.
Considering downstream companies need regularly do code merge with release code, each time version modification is after cut branch. In other words, each version modification commit is not on git main tree, which results in conflict on codebases of downstream companies.

**Comment by ysh329** [comment]
Hi all, due to a new idea about release flow before and after cut branch, this release may delay. More informations can refer below PRs:
- https://github.com/apache/tvm/pull/15847
- https://github.com/apache/tvm/pull/15934

**Comment by ysh329** [comment]
Hi all, with help of @Hzfengsy, branch v0.14.0 was created. However, because PR about version modification merged without sqaush, related commit is unverified, more concretely referring [Rebased commits by the web interface aren't signed](https://github.com/orgs/community/discussions/11639).

Thus, this unverfied commit about version modification whether exists potential risks on v0.14.0 sush as chain reaction, especially when cherry-pick is required.

**Comment by ysh329** [comment]
> Hi all, with help of @Hzfengsy, branch v0.14.0 was created. However, because PR about version modification merged without sqaush, related commit is unverified, more concretely referring [Rebased commits by the web interface aren't signed](https://github.com/orgs/community/discussions/11639).
> 
> Thus, this unverfied commit about version modification whether exists potential risks on v0.14.0 sush as chain reaction, especially when cherry-pick is required. It may be necessary to do some experiments such as Cherry Pick, but there are currently no new commit merged on main.

I made a bugfix cherry-pick PR: https://github.com/apache/tvm/pull/15946, to check this new flow whether any problem exists.

**Comment by ysh329** [comment]
Hi all, with help of @Hzfengsy , candidate package uploaded.

## Check sha512

```shell
@ysh329 ➜ /workspaces/tmp $ shasum -a 512 ./apache-tvm-src-v0.14.0.rc0.tar.gz
223335470a249f3bd357ac385f6b7820dc6b400e572e71f8180107e7d8c2960a3e1dd6ee89327f65072d643c324c09b91b16586ecdf7bfc8eb4d7a0a17de0b27  ./apache-tvm-src-v0.14.0.rc0.tar.gz
@ysh329 ➜ /workspaces/tmp $ cat ./apache-tvm-src-v0.14.0.rc0.tar.gz.sha512 
223335470a249f3bd357ac385f6b7820dc6b400e572e71f8180107e7d8c2960a3e1dd6ee89327f65072d643c324c09b91b16586ecdf7bfc8eb4d7a0a17de0b27  apache-tvm-src-v0.14.0.rc0.tar.gz
```

## Check asc


```shell
@ysh329 ➜ /workspaces/tmp/apache-tvm-src-v0.14.0 $ gpg --import ./KEYS
gpg: key 6754EA97C55E3DEB: public key "Tianqi Chen (CODE SIGNING KEY) <tqchen@apache.org>" imported
gpg: key 8955D84E20C9AB0C: public key "Yizhi Liu <javelinjs@gmail.com>" imported
gpg: key 3A709F6F2B86E9D6: public key "Yizhi Liu (Yizhi Liu at Apache) <liuyizhi@apache.org>" imported
gpg: key CA751254E97B9FE4: public key "Yizhi Liu <liuyizhi@apache.org>" imported
gpg: key ED03B26E4FC3509F: public key "Ziheng Jiang <ziheng@apache.org>" imported
gpg: key 9FBECBD3D75EFD4B: public key "Zhi Chen <zhic@apache.org>" imported
gpg: key 35ABC9676004ADAE: public key "Junru Shao <junrushao@apache.org>" imported
gpg: key 2C75E5A496C80880: public key "Wuwei Lin <wuwei@apache.org>" imported
gpg: key 07FA463F1C926F48: public key "David Riazati <driazati@apache.org>" imported
gpg: key C9A56ABD5CCA3EB8: public key "Andrew Zhao Luo <andrewzhaoluo@apache.org>" imported
gpg: key 28D4862222B8EC31: public key "Leandro Nunes <leandron@apache.org>" imported
gpg: key 06D051CA84EF3749: public key "Siyuan Feng (CODE SIGNING KEY) <syfeng@apache.org>" imported
gpg: Total number processed: 12
gpg:               imported: 12
@ysh329 ➜ /workspaces/tmp/apache-tvm-src-v0.14.0 $ gpg --edit-key 664EF29634C05669C3DCF83106D051CA84EF3749
gpg (GnuPG) 2.2.19; Copyright (C) 2019 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


pub  rsa4096/06D051CA84EF3749
     created: 2023-05-05  expires: never       usage: SC  
     trust: unknown       validity: unknown
sub  rsa4096/D0064A60FA06DD20
     created: 2023-05-05  expires: never       usage: E   
[ unknown] (1). Siyuan Feng (CODE SIGNING KEY) <syfeng@apache.org>

gpg> trust
pub  rsa4096/06D051CA84EF3749
     created: 2023-05-05  expires: never       usage: SC  
     trust: unknown       validity: unknown
sub  rsa4096/D0064A60FA06DD20
     created: 2023-05-05  expires: never       usage: E   
[ unknown] (1). Siyuan Feng (CODE SIGNING KEY) <syfeng@apache.org>

Please decide how far you trust this user to correctly verify other users' keys
(by looking at passports, checking fingerprints from different sources, etc.)

  1 = I don't know or won't say
  2 = I do NOT trust
  3 = I trust marginally
  4 = I trust fully
  5 = I trust ultimately
  m = back to the main menu

Your decision? 5
Do you really want to set this key to ultimate trust? (y/N) y

pub  rsa4096/06D051CA84EF3749
     created: 2023-05-05  expires: never       usage: SC  
     trust: ultimate      validity: unknown
sub  rsa4096/D0064A60FA06DD20
     created: 2023-05-05  expires: never       usage: E   
[ unknown] (1). Siyuan Feng (CODE SIGNING KEY) <syfeng@apache.org>
Please note that the shown key validity is not necessarily correct
unless you restart the program.

gpg> quit
@ysh329 ➜ /workspaces/tmp/apache-tvm-src-v0.14.0 $ gpg --verify ../apache-tvm-src-v0.14.0.rc0.tar.gz.asc ../apache-tvm-src-v0.14.0.rc0.tar.gz
gpg: Signature made Mon Oct 23 07:30:46 2023 UTC
gpg:                using RSA key 664EF29634C05669C3DCF83106D051CA84EF3749
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: next trustdb check due at 2025-10-14
gpg: Good signature from "Siyuan Feng (CODE SIGNING KEY) <syfeng@apache.org>" [ultimate]
```

## Check binary in source code

```shell
# check binary
$ find ./apache-tvm-src-v0.14.0 -type f -exec file {} + | grep -w "ELF\|shared object"
# find nothing
```

## Compile and Python Import on Linux

```shell
```

**Comment by ysh329** [comment]
Hi all, vote starts (https://github.com/apache/tvm/issues/15974). Everyone is welcomed to vote. Please vote by replying to this thread explicitly. Vote will close July. 20th at 23:59M GMT.

**Comment by ysh329** [comment]
Hi all, [vote passes](https://github.com/apache/tvm/issues/16022), next we'll [upload the binaries to Apache mirrors and create a new release TAG](https://tvm.apache.org/docs/contribute/release_process.html#post-the-release) named v0.14.0 meanwhile remove the pre-release candidate TAG v0.14.0.rc0. This program needs help please.

Besides, we need update doc website too. According to [last release talk](https://github.com/apache/tvm/issues/14505#issuecomment-1546528974_) as below, this step would need ASF perm.

cc @Hzfengsy @vinx13 @tqchen

**Comment by ysh329** [comment]
Due to this release with new release flow about version number modification, I made a PR for release docs: https://github.com/apache/tvm/pull/16024.

**Comment by ysh329** [comment]
Hi @vinx13 , can you help update docs to website?

**Comment by ysh329** [comment]
Hi all, do we have an example of how to generate website documents?
Based on our previous release experience, currently the method of generating website documents in TVM documents is not working.

**Comment by vinx13** [comment]
the documents can be built via docker or downloaded from the built artifacts generated by CI (there's a link in the ci output). we should update the website with this process

**Comment by ysh329** [comment]
> the documents can be built via docker or downloaded from the built artifacts generated by CI (there's a link in the ci output). we should update the website with this process

Let me have a try. It sounds trouble via docker. I didn't find link in cherry-pick PR CI output: https://github.com/apache/tvm/actions/runs/6559196548/job/17814307171.

**Comment by vinx13** [comment]
the link is in Jenkins ci step that uploads the artifact but I believe the link has expired

**Comment by vinx13** [comment]
it's possible that we modify jenkinsfile to enable automatic deployment of docs for release branch https://github.com/apache/tvm/blob/main/ci/jenkins/templates/gpu_jenkinsfile.groovy.j2#L157-L215

**Comment by ysh329** [comment]
> it's possible that we modify jenkinsfile to enable automatic deployment of docs for release branch https://github.com/apache/tvm/blob/main/ci/jenkins/templates/gpu_jenkinsfile.groovy.j2#L157-L215

Great! Let me familiarize myself with this Jenkins.
