### ISSUE TITLE
[Release] v0.15.0 release schedule

### ISSUE THREAD

**Issue by ysh329** [apache/tvm#16277]
> [Last release v0.14.0](https://github.com/apache/tvm/releases/tag/v0.14.0) was proposed at the end of September and the release day is 23 Oct, more detail refer [v0.14.0 release schedule](https://github.com/apache/tvm/issues/15812). It has been almost **three months** since 1 Oct. According to our [RFC-0067 about quarter-based releases](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md), I **hope to release v0.15.0 version at the end of January 2024**. It's meaningful especially for **AI infra companies which needs regularly merge with release version.**
**In order to continue with our agreed release cycle as per discussion in [RFC#67](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md) , I'd like to propose a schedule for our next TVM release: `v0.15.0`.**

This schedule is tentative and may change as we progress through the process. In case dates change, this thread will be kept updated.

The proposed schedule is:

- [x] **2 Jan 2024** Following three actions should be continuous and coherent:
  - [x] Make version modification twice as two commits: first to `v0.15.0` on main branch; second to `v0.16.dev0` on main branch in one PR, and **merged without squash (required)**. Why do this first [referring discuss on v0.14.0 release](https://github.com/apache/tvm/issues/15134#issuecomment-1607649151): https://github.com/apache/tvm/pull/16326
  - [x] A branch `v0.15.0` to be created from `main` on first commit: https://github.com/apache/tvm/tree/v0.15.0
  - [x] A tag named `v0.15.0.rc0` created on first commit: https://github.com/apache/tvm/releases/tag/v0.15.0.rc0
  - [x] A tag named `v0.16.dev0` created on second commit: https://github.com/apache/tvm/releases/tag/v0.16.dev0
- [x] **5 Jan 2024** - Cherry-picking soft deadline
  - During this time any reasonable change can be merged, comment on this issue with the commit you would like added to the release branch
- [x] **9 Jan 2024** - Cherry-picking **hard deadline**
  - During this time only critical changes will be merged, comment on this issue with the commit you would like added to the release branch as well as the reasoning for adding it
- [x] **9 Jan 2024** - Draft release notes published: https://github.com/apache/tvm/issues/16391
- [x] **12 Jan 2024** - [Prepare release candidate packaging `v0.15.0.rc0` and uploading](https://tvm.apache.org/docs/contribute/release_process.html#upload-the-release-candidate)
  - Create tag `v0.15.0.rc0`: https://github.com/apache/tvm/releases/tag/v0.15.0.rc0
  - Github release page: https://github.com/apache/tvm/releases/tag/v0.15.0.rc0
  - Upload to Apache repo: https://dist.apache.org/repos/dist/dev/tvm/tvm-v0.15.0-rc0/
- [x] **~12~ 19 Jan 2024** - Release voting opens: https://github.com/apache/tvm/issues/16428
- [ ] **~22~ 25 Jan 2024**
  - [x] Voting result: https://github.com/apache/tvm/issues/16475
  - [x] Create a new release tag `v0.15.0` on last commit on release branch: https://github.com/apache/tvm/releases/tag/v0.15.0
  - [x] Change pre-release as latest release: https://github.com/apache/tvm/releases/tag/v0.15.0
  - [ ] Upload the binaries to Apache mirrors: <link>
- [x] **~22~ 25 Jan 2024** - Release date
- [ ] **~22~ 25 Jan 2024** - Update the TVM Website

**Call for release managers:** In case you want to be involved in upcoming releases, please manifest your interest in this thread and we'll try to organise. 😆

See also:

- [Release steps](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md#reference-level-explanation)
- [TVM release process docs](https://tvm.apache.org/docs/contribute/release_process.html).

cc @apache/tvm-committers [@Hzfengsy](https://github.com/Hzfengsy) [@vinx13](https://github.com/vinx13)  [@areusch](https://github.com/areusch) [@Mousius](https://github.com/Mousius) [@tqchen](https://github.com/tqchen) [@AndrewZhaoLuo](https://github.com/AndrewZhaoLuo) [@Johnson9009](https://github.com/Johnson9009)

**Comment by ysh329** [comment]
Hi all, make version modification twice as two commits in one PR merged (https://github.com/apache/tvm/pull/16326). We need:

1. Create a branch named v0.15.0 from main on first commit(7445b8723c64e00e65f1f875094e14e5f340b161);
2. Create a tag named v0.15.0.rc0 on first commit(7445b8723c64e00e65f1f875094e14e5f340b161);
3. Create a tag named v0.16.dev0 created on second commit(e69363ab1e594e946ce261f9a2d7d44ef10fda56).

cc @Hzfengsy @vinx13 @tqchen

**Comment by ysh329** [comment]
git tag

> Hi all, make version modification twice as two commits in one PR merged (#16326). We need:
> 
> 1. Create a branch named v0.15.0 from main on first commit([7445b87](https://github.com/apache/tvm/commit/7445b8723c64e00e65f1f875094e14e5f340b161));
> 2. Create a tag named v0.15.0.rc0 on first commit([7445b87](https://github.com/apache/tvm/commit/7445b8723c64e00e65f1f875094e14e5f340b161));
> 3. Create a tag named v0.16.dev0 created on second commit([e69363a](https://github.com/apache/tvm/commit/e69363ab1e594e946ce261f9a2d7d44ef10fda56)).
> 
> I don't know how to push tags/branch created on my own repo to apache/tvm's? I didn't find about create branch by Web UI as below in apache/tvm:
> 
> ![image](https://private-user-images.githubusercontent.com/7320657/294095524-fd809e86-140f-4e19-beb2-0601bf60a3f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDcxNjIsIm5iZiI6MTcwNDM0Njg2MiwicGF0aCI6Ii83MzIwNjU3LzI5NDA5NTUyNC1mZDgwOWU4Ni0xNDBmLTRlMTktYmViMi0wNjAxYmY2MGEzZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMDU0MTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Q2ZGI0MzBlYjQwZGZiNTVlYmEzMWE5MDkzNzYyY2Q0OGFhZTRlNTQ1Yjg3MTFiZGMxZWY2Njg3ODc4NGYwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M_Z1nep-mO7ZLAYuMwCX1oYsq2CYm2-EzLrDr4e0a-s)
> 
> ![image](https://private-user-images.githubusercontent.com/7320657/294095692-f90fdd4a-47a5-4449-b5f9-bb18531afe77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDcxNjIsIm5iZiI6MTcwNDM0Njg2MiwicGF0aCI6Ii83MzIwNjU3LzI5NDA5NTY5Mi1mOTBmZGQ0YS00N2E1LTQ0NDktYjVmOS1iYjE4NTMxYWZlNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMDU0MTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM4YTAwNjYxMjgzNTg3NjJmMjZjYjg4Zjc3YTk3NWU2N2JhZGYwNmMxMzJlMmM2Y2NjNGVhNTMxZmMwNDU3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gPzfhAD82c3oflKwiuOBGYkW8yyhK4DhhCwizdfQzTs)

Besides, I push tags and branch created by command line to my own repo. However, I don't know how to push to apache/tvm.

cc @Hzfengsy @vinx13 @tqchen

**Comment by vinx13** [comment]
@ysh329  a tag will be created automatically if you create a release on GitHub

**Comment by ysh329** [comment]
> @ysh329 a tag will be created automatically if you create a release on GitHub

I found this **Create a release** link in my own tvm repo:

![image](https://github.com/apache/tvm/assets/7320657/44d83800-2715-4aff-bc43-672414cf8c3d)

but find nothing below apache/tvm repo:

![image](https://github.com/apache/tvm/assets/7320657/01769367-3ca9-4fd0-b430-618fbe15aa9d)

cc @Hzfengsy @vinx13

**Comment by vinx13** [comment]
@ysh329 you may need to setup your github account following https://cwiki.apache.org/confluence/display/OPENWHISK/Accessing+Apache+GitHub+as+a+Committer

**Comment by ysh329** [comment]
> @ysh329 you may need to setup your github account following https://cwiki.apache.org/confluence/display/OPENWHISK/Accessing+Apache+GitHub+as+a+Committer

Oh, u r right.

**Comment by ysh329** [comment]
Hi all, may delay few days, may some issue when I register iCLA previous. I resend a register email. If anyone has cherry-pick PR, please notify in this thread.

**Comment by ysh329** [comment]
> Hi all, make version modification twice as two commits in one PR merged (#16326). We need:
> 
> 1. Create a branch named v0.15.0 from main on first commit([7445b87](https://github.com/apache/tvm/commit/7445b8723c64e00e65f1f875094e14e5f340b161));
> 2. Create a tag named v0.15.0.rc0 on first commit([7445b87](https://github.com/apache/tvm/commit/7445b8723c64e00e65f1f875094e14e5f340b161));
> 3. Create a tag named v0.16.dev0 created on second commit([e69363a](https://github.com/apache/tvm/commit/e69363ab1e594e946ce261f9a2d7d44ef10fda56)).

Hi all, branch and tags created.

**Comment by ysh329** [comment]
Hi all, due to cherry-pick PR about release signing, I update the tag v0.15.0.rc0 to new commit: a340dbed7353a5ef24e72b73fe8fff3665f3359a.

**Comment by ysh329** [comment]
Hi all, vote starts (https://github.com/apache/tvm/issues/16428). Everyone is welcomed to vote. Please vote by replying to this thread (https://github.com/apache/tvm/issues/16428) explicitly. Vote will close Jan. 25th at 23:59M GMT.

**Comment by ysh329** [comment]
Hi all, github tag v0.15.0 created and release page updated. Please help update apache svn repo, because it need authority:

> After the vote passes, to upload the binaries to Apache mirrors, you move the binaries from dev directory (this should be where they are voted) to release directory. This “moving” is the only way you can add stuff to the actual release directory. (**Note: only PMC can move to release directory**)
From doc about post the release: https://tvm.apache.org/docs/contribute/release_process.html?highlight=release#post-the-release

cc @Hzfengsy @junrushao @tqchen
