### ISSUE TITLE
[Tracking Issue] Remove MXNet Dependency

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#16547]
MXNet has been archived and likely future versions of tvm should not depend on it. This is a tracking issue for us to remove the related stale testcases and documentations that depends on mxnet

**Comment by Lunderberg** [comment]
I have a rough list of the impacted files that will need to be updated, from putting together #16546

- [ ] Depend on mxnet's AWS
  - [ ] `gallery/how_to/compile_models/from_mxnet.py`
  - [ ] `gallery/how_to/deploy_models/deploy_model_on_nano.py`
  - [ ] `gallery/how_to/deploy_models/deploy_model_on_rasp.py`
  - [ ] `gallery/how_to/deploy_models/deploy_quantized.py`
  - [ ] `gallery/how_to/extend_tvm/bring_your_own_datatypes.py`
  - [ ] `gallery/how_to/tune_with_autoscheduler/tune_network_arm.py`
  - [ ] `gallery/how_to/tune_with_autoscheduler/tune_network_cuda.py`
  - [ ] `gallery/how_to/tune_with_autoscheduler/tune_network_mali.py`
  - [ ] `gallery/how_to/tune_with_autoscheduler/tune_network_x86.py`
  - [ ] `rust/tvm/examples/resnet`
  - [ ] `tests/python/frontend/mxnet/test_forward.py`
  - [ ] `vta/scripts/tune_resnet.py`
  - [ ] `vta/tutorials/autotvm/tune_alu_vta.py`
  - [ ] `vta/tutorials/autotvm/tune_relay_vta.py`
  - [ ] `vta/tutorials/frontend/deploy_classification.py`
  
  
- [ ] Depend on mxnet's AWS (commented out for CI)
  - [ ] `gallary/how_to/tune_with_autoscheduler/tune_network_cuda.py`
  - [ ] `gallary/how_to/tune_with_autoscheduler/tune_network_mali.py`
  - [ ] `gallary/how_to/tune_with_autoscheduler/tune_sparse_x86.py`
  - [ ] `gallary/how_to/tune_with_autoscheduler/tune_network_arm.py`
  - [ ] `gallary/how_to/tune_with_autoscheduler/tune_conv2d_layer_cuda.py`
  - [ ] `gallary/how_to/tune_with_autoscheduler/tune_conv2d_layer_cuda.py`
  - [ ] `gallary/how_to/tune_with_autoscheduler/tune_network_x86.py`
  - [ ] `gallary/how_to/tune_with_autotvm/tune_conv2d_cuda.py`
  - [ ] `gallary/how_to/tune_with_autotvm/tune_relay_arm.py`
  - [ ] `gallary/how_to/tune_with_autotvm/tune_relay_x86.py`
  - [ ] `gallary/how_to/tune_with_autotvm/tune_relay_mobile_gpu.py`
  - [ ] `gallary/how_to/tune_with_autotvm/tune_relay_cuda.py`

- [ ] Depend on https://github.com/dmlc/mxnet.js
  - [ ] `gallery/how_to/deploy_models/deploy_model_on_android.py`

**Comment by Hzfengsy** [comment]
Updates: https://github.com/apache/tvm/pull/16572
