### ISSUE TITLE
[Release] v0.17.0 release schedule

### ISSUE THREAD

**Issue by ysh329** [apache/tvm#17122]
> [Last release v0.16.0](https://github.com/apache/tvm/issues/16857) was proposed at the end of April. and the release day is 27 April, more detail refer [v0.16.0 release schedule](https://github.com/apache/tvm/issues/16857). It has been almost **three months** since April. According to our [RFC-0067 about quarter-based releases](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md), I **hope to release v0.17.0 version at the end of July 2024**. It's meaningful especially for **AI infra companies which needs regularly merge with release version.**
**In order to continue with our agreed release cycle as per discussion in [RFC#67](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md) , I'd like to propose a schedule for our next TVM release: `v0.17.0`.**

This schedule is tentative and may change as we progress through the process. In case dates change, this thread will be kept updated.

The proposed schedule is:

- [x] **12 July. 2024** Following three actions should be continuous and coherent:
  - [x] Make version modification twice as two commits: first to `v0.17.0` on main branch; second to `v0.18.dev0` on main branch in one PR, and **merged without squash (required)**. Why do this first [referring discuss on v0.14.0 release](https://github.com/apache/tvm/issues/15134#issuecomment-1607649151): https://github.com/apache/tvm/pull/17156
  - [x] A branch `v0.17.0` to be created from `main` on first commit: https://github.com/apache/tvm/tree/v0.17.0
  - [x] A tag named `v0.17.0.rc0` created on first commit: https://github.com/apache/tvm/releases/tag/v0.17.0.rc0
  - [x] A tag named `v0.18.dev0` created on second commit: https://github.com/apache/tvm/releases/tag/v0.18.dev0
- [x] **16 July. 2024** - Cherry-picking soft deadline
  - During this time any reasonable change can be merged, comment on this issue with the commit you would like added to the release branch
- [x] **20 July. 2024** - Cherry-picking **hard deadline**
  - During this time only critical changes will be merged, comment on this issue with the commit you would like added to the release branch as well as the reasoning for adding it
  - Consider https://github.com/apache/tvm/issues/17114
- [x] **20 July. 2024** - Draft release notes published: https://github.com/apache/tvm/issues/17178
- [x] **20 July. 2024** - [Prepare release candidate packaging `v0.17.0.rc0` and uploading](https://tvm.apache.org/docs/contribute/release_process.html#upload-the-release-candidate)
  - Create tag `v0.17.0.rc0`: https://github.com/apache/tvm/releases/tag/v0.17.0.rc0
  - Github release page from tag: https://github.com/apache/tvm/releases/tag/v0.17.0.rc0
  - Upload to Apache repo: https://dist.apache.org/repos/dist/dev/tvm/tvm-v0.17.0-rc0/
- [x] **20 July. 2024** - Release voting opens: https://github.com/apache/tvm/issues/17179
- [ ] **25 July. 2024**
  - [x] Voting result: https://github.com/apache/tvm/issues/17196
  - [x] Create a new release tag `v0.17.0` on last commit on release branch: https://github.com/apache/tvm/releases/tag/v0.17.0
  - [x] Change pre-release as latest release: https://github.com/apache/tvm/releases/tag/v0.17.0
  - [ ] Upload the binaries to Apache mirrors: <link>
- [x] **25 July. 2024** - Release date
- [ ] **26 July. 2024** - Update the TVM Website

**Call for release managers:** In case you want to be involved in upcoming releases, please manifest your interest in this thread and we'll try to organise. 😆

See also:

- [Release steps](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md#reference-level-explanation)
- [TVM release process docs](https://tvm.apache.org/docs/contribute/release_process.html).

cc @apache/tvm-committers [@Hzfengsy](https://github.com/Hzfengsy) [@vinx13](https://github.com/vinx13)  [@areusch](https://github.com/areusch) [@Mousius](https://github.com/Mousius) [@tqchen](https://github.com/tqchen) [@AndrewZhaoLuo](https://github.com/AndrewZhaoLuo) [@Johnson9009](https://github.com/Johnson9009)
