### ISSUE TITLE
[Tracking Issue] Remove `distutils` dependency from the codebase

### ISSUE THREAD

**Issue by mshr-h** [apache/tvm#17172]
Because python >=3.12 does not ship `distutils` anymore.
https://peps.python.org/pep-0632/#migration-advice

Belows are the modules we use.
- [x] distutils.version.LooseVersion #17173 
- [x] distutils.util.strtobool #17185
- [ ] distutils.core.setup
- [ ] distutils.extension.Extension
- [ ] distutils.log.debug
