### ISSUE TITLE
[Release] v0.19.0 release schedule

### ISSUE THREAD

**Issue by ysh329** [apache/tvm#17575]
> [Last release v0.18.0](https://github.com/apache/tvm/issues/17412) was proposed at the end of September. and the release day is 21 Oct., more detail refer [v0.18.0 release schedule](https://github.com/apache/tvm/issues/17412). It has been almost **three months** since September. According to our [RFC-0067 about quarter-based releases](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md), I **hope to release v0.19.0 version at the end of Jan. 2025**. It's meaningful especially for **AI infra companies which needs regularly merge with release version.**
**In order to continue with our agreed release cycle as per discussion in [RFC#67](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md) , I'd like to propose a schedule for our next TVM release: `v0.19.0`.**

This schedule is tentative and may change as we progress through the process. In case dates change, this thread will be kept updated.

The proposed schedule is:

- [x] **8 Jan. 2025** Following three actions should be continuous and coherent:
  - [x] Make version modification twice as two commits: first to `v0.19.0` on main branch; second to `v0.20.dev0` on main branch in one PR, and **merged without squash (required)**. Why do this first [referring discuss on v0.14.0 release](https://github.com/apache/tvm/issues/15134#issuecomment-1607649151): https://github.com/apache/tvm/pull/17586
  - [x] A branch `v0.19.0` to be created from `main` on first commit: https://github.com/apache/tvm/tree/v0.19.0
  - [x] A tag named `v0.19.0.rc0` created on first commit: https://github.com/apache/tvm/releases/tag/v0.19.0.rc0 
  - [x] A tag named `v0.20.dev0` created on second commit: https://github.com/apache/tvm/releases/tag/v0.20.dev0
- [x] **12 Jan. 2025** - Cherry-picking soft deadline
  - During this time any reasonable change can be merged, comment on this issue with the commit you would like added to the release branch
- [x] **16 Jan. 2025** - Cherry-picking **hard deadline**
  - During this time only critical changes will be merged, comment on this issue with the commit you would like added to the release branch as well as the reasoning for adding it
  - Consider https://github.com/apache/tvm/issues/17564
- [x] **~~16~~ 24 Jan. 2025** - Draft release notes published: https://github.com/apache/tvm/issues/17600
- [x] **~~16~~ 24 Jan. 2025** - [Prepare release candidate packaging `v0.19.0.rc0` and uploading](https://tvm.apache.org/docs/contribute/release_process.html#upload-the-release-candidate)
  - [x] Create tag `v0.19.0.rc0`: https://github.com/apache/tvm/releases/tag/v0.19.0.rc0 
  - [x] Github release page from tag: https://github.com/apache/tvm/releases/tag/v0.19.0.rc0
  - [x] Upload to Apache repo: https://dist.apache.org/repos/dist/dev/tvm/tvm-v0.19.0-rc0/
- [x] **~~16~~ 24 Jan. 2025** - Release voting opens: https://github.com/apache/tvm/issues/17602
- [x] **27 Jan. 2025**
  - [x] Voting result: https://github.com/apache/tvm/issues/17612
  - [x] Create a new release tag `v0.19.0` on last commit on release branch: https://github.com/apache/tvm/releases/tag/v0.19.0
  - [x] Change pre-release as latest release: https://github.com/apache/tvm/releases/tag/v0.19.0
  - [x] Upload the binaries to Apache mirrors: https://dist.apache.org/repos/dist/release/tvm/tvm-v0.19.0/
- [x] **27 Jan. 2025** - Release date
- [x] **27 Jan. 2025** - Update the TVM Website
    - [x] Create a PR on main branch for tvm-site (from **yourself owner repo**): https://github.com/apache/tvm-site/pull/48
    - [x] Execute script on main branch for tvm-site (from **apache owner repo**): execute `scripts/task_deploy_asf_site.sh`
    - [x] https://dist.apache.org/repos/dist/release/tvm/tvm-v0.19.0/, https://www.apache.org/dyn/closer.lua/tvm/tvm-v0.19.0/

**Call for release managers:** In case you want to be involved in upcoming releases, please manifest your interest in this thread and we'll try to organise. 😆

See also:

- [Release steps](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md#reference-level-explanation)
- [TVM release process docs](https://tvm.apache.org/docs/contribute/release_process.html).

cc @apache/tvm-committers [@Hzfengsy](https://github.com/Hzfengsy) [@vinx13](https://github.com/vinx13)  [@areusch](https://github.com/areusch) [@Mousius](https://github.com/Mousius) [@tqchen](https://github.com/tqchen) [@AndrewZhaoLuo](https://github.com/AndrewZhaoLuo) [@Johnson9009](https://github.com/Johnson9009) [@yongwww](https://github.com/yongwww)

**Comment by ysh329** [comment]
Hi all, due to CI issue (the ARM build issue is due to memory limits. We're looking into upgrading the instance type or adding swap space](https://github.com/apache/tvm/issues/17586#issuecomment-2587390434_), release will be postponed.

**Comment by ysh329** [comment]
Hi all, the [vote starts](https://github.com/apache/tvm/issues/17602) and will close Jan 27th at 23:59M GMT.

**Comment by ysh329** [comment]
Hi all, v0.19.0 released (https://github.com/apache/tvm/releases/tag/v0.19.0), website updated.
