### ISSUE TITLE
[Parser][Tracking] Parsing and Pretty Printing 2.0 for Error Reporting 

### ISSUE THREAD

**Issue by jroesch** [apache/tvm#6153]
Following my suggestion to keep a tracking issue for big work items like Ansor. I will keep a tracking issue for all the work being done on the Parser 2.0. I will track remaining todo items and their completion here. Will update when I open second PR shortly. 

- [ ] Add support for tokenizing escape sequences correctly in string literals. 
- [ ] Update lexer to use diagnostic context. 
- [ ] Add spans to match clauses.
- [ ] Export optional span arguments to Python bindings. 
- [ ] Add spans to constructors and type data. 
- [ ] Address spans for variables, global variables, and ops.
- [ ] Support mutating spans in ExprMutator, and update CoW logic. 
- [ ] Define a customizable `Render` for controlling the rendering behavior of diagnostics. 
- [ ] Add a better implementation for matching operator strings. 
- [ ] Fix oddity with tuple type parsing, i.e (A) is not equal (A,)
- [ ] Clean up attribute printing and parsing around null values. 
- [ ] Discuss reference syntax, currently downgraded to simpler to parse (ref_read/ref_write).
- [ ] Handle null Span and SourceMap gracefully. 
- [ ] Handle eta-conversion of constructors during parsing
```
def @rev[A](%xs: List[A]) -> List[A] {
  - @foldl(@flip(Cons), Nil, %xs)
  + @foldl(@flip(fn (%h: A, %t: List[A]) { Cons(%h, %t) }), Nil, %xs)
```
- Revisit some printing sugar as it was previously unsound wrt to the parser i.e printing of curly braces for blocks.

**Comment by jroesch** [comment]
See also #6617
