### ISSUE TITLE
[RFC] Tracking Issue for TECompiler

### ISSUE THREAD

**Issue by jroesch** [apache/tvm#7526]
Tracking issue for [te_compiler](https://discuss.tvm.apache.org/t/rfc-relay-tecompiler-rewrite-existing-compile-engine-to-match-updated-compiler-flow/9233).

### About tracking issues
Tracking issues are used to record the overall progress of implementation and relevant issues.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
For open ended discussion, check out: https://discuss.tvm.apache.org/. 

### Implementation
- [ ] Introduce TECompiler (see #7518)
- [ ] Unify tvm::lower into a single API
  * [ ] Remove lower wrapper inside of te_compiler_cache
- [ ] Rewrite GraphRuntimeCodegen
- [ ] Rewrite Interpreter
- [ ] Rewrite VM
- [ ] Handle BYOC Modules 

### Unresolved Questions
How to unify passes across backends?

**Comment by Mousius** [comment]
@jroesch are there plans to include AOT in this now?

**Comment by jroesch** [comment]
cc @mbs-octoml @denise-k is it possible for you guys to take over this one as you now have the most context?

**Comment by mbs-octoml** [comment]
Here's where we've gotten to:
 1. TECompiler has fully replaced CompileEngine :-)
 2. te_complier_cache.cc still in pretty messy state, the cache datastructures themselves can be simplified however we still have customers of TECompiler::Lower etc via te_compiler.py.
 3. After #9483 all backends will use the TELowerPass instead of the one-function-at-a-time lowering API.
 4. IRModule could do with better support for external functions, runtime::Modules and generated AOT source code.

At some point I'd lie to tackle 2 head-on, that will require discussion to figure out how to move folks off of depending on the CCache* structures and one-function-at-a-time.

And 4 can also be split out.

Close this one?

**Comment by jroesch** [comment]
Ok Mark will split out into follow up issues that go on the roadmap and we will close this one. cc @Mousius
