### ISSUE TITLE
[RFC][Tracking Issue] TensorIR Scheduling

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7527]
This is a global tracking issue for landing the initial PRs of TensorIR scheduling. The original RFC can be found [here](https://discuss.tvm.apache.org/t/rfc-tensorir-a-schedulable-ir-for-tvm/7872). Please feel free to bring in more questions to the corresponding thread. 

To make the improvement manageable, we will be breaking the code into several steps. The main architecture scaffolding and 
data structure changes will come first, then we will upstream individual scheduling primitives in a incremental way, where each component are self-contained.

## Key Data Structures

The following key data structures will be introduced to handle the support of TensorIR.
Logically the data structures belongs to the following layers:

- D0: Block and BlockRealize: these are nodes to enable the block declarations in the stmt
- D1: ScheduleState: an auxiliary data structure to encode additional dependency information used for schedule transformations
    - Most schedule primitives can be viewed as a ScheduleState => ScheduleState transformations
    - We will also introduce SRef, a reference pointer to the AST (to refer to loop and blocks) to facilitate transformations
- D2: Schedule: interface for running schedule transformations, like the current te.schedule

These data structures will form the initial scafolds. The transformation primitives will then become like passes, that only depends on D0 and D1. The each primitive will be exposed to an user facing API via D2.

## Steps

- [x] M1a PR0: The additional data structure needed for TensorIR, in particular the Block structure, changes to related fields. #7553
- [x] M1a PR1: Changes to the tvmscript parser, printer to allow us to ingest and print the new data structures. #7630
- [x] M1b PR0: Initial scaffolding of ScheduleState and Schedule data structure with basic utils and no primitives
    - [x] Enhancing visitors #7627
    - [x] Arithmetic analysis on iter-affine-map: #7759  #7760
    - [x] Core data structure: ScheduleState #7765
    - [x] The schedule class #7847 
- [x] M1c PRs: Overall lowering API to lower a new TIR function to the codegen. 
     - [x] LowerInitBlock: #7806
     - [x] LCA detection for buffer allocation site: #7848
     - [x] Plan and update buffer allocation location: #7873
     - [x] Compact buffer allocation: #7923
     - [x] Flatten buffer: Flatten buffer access into 1D (similar to storage flatten in the mainline) #7962 
     - [x] Lower and build TensorIR: #8044
     - [x] Sub-region buffer match: #8585
     - [x] VerifyBufferMatch (optional for now, verify that buffer layout constraints are met in sub region matches)
     - [x] Create TIR from TE: #7987
- [x] M2a PRs: multiple PRs to support scheduling primitives, one PR per primitive, with related test-cases.
     - [x] Checks for region cover property #8114
     - [x] Structural error reporting in schedule primitives #8121
     - [x] Primitive: compute-inline & reverse-compute-inline #8170
     - [x] Primitive: fuse & split #8467
     - [x] Primitive: rfactor #8544
     - [x] Primitive: storage-align #8693 
     - [x] Primitive: vectorize & unroll & bind thread #8716
     - [x] Primitive: reorder #8767
     - [x] Primitive: cache-read & cache-write #8863
     - [x] Primitive: compute-at & reverse-compute-at #8943 
     - [x] Primitive: decompose-reduction #9041

**Comment by tqchen** [comment]
key data structures are updated as per @jcf94 's comment

**Comment by manupa-arm** [comment]
Thanks @junrushao1994.

**Comment by tqchen** [comment]
All the items are merged as of today. As a result, this issue is closed. Thanks everyone for pushing and landing this major effort.
