### ISSUE TITLE
[RFC][Tracking Issue] Additional Target Hooks

### ISSUE THREAD

**Issue by Mousius** [apache/tvm#8589]
1. [x] Add hook for relay_to_tir - https://github.com/apache/tvm/pull/8423
1. [x] Add hook for tir_to_runtime - 
1. [ ] Migrate `relay.ext` to relay_to_runtime / constant_updater -
1. [ ] Migrate external codegen -> target conversion -
