### ISSUE TITLE
[RFC][Tracking Issue] Pipeline Executor For Compute graph pipeline

### ISSUE THREAD

**Issue by huajsj** [apache/tvm#8596]
PR  https://github.com/apache/tvm/pull/7892
Discussion https://discuss.tvm.apache.org/t/rfc-compute-graph-pipeline-with-new-subgraph-executor/9839/

# Steps
Following are the PR list for the feature plan
## [Pipeline Executor] Infrastructure 
- [x] Pipeline configuration creation https://github.com/apache/tvm/pull/8702
- [x]  Pipeline backend build and pipeline configuration export/load https://github.com/apache/tvm/pull/9108
- [x] Pipeline executor set_input implementation and  input configuration loading. https://github.com/apache/tvm/pull/9751
- [x] Pipeline executor set_params  implementation and  params configuration loading.  https://github.com/apache/tvm/pull/9846
- [x] Pipeline executor runtime interface declare and implementation.https://github.com/apache/tvm/pull/10010
- [x] Pipeline executor pipe line sequence execution. https://github.com/apache/tvm/pull/10082
- [x] Pipeline executor, pipeline execution, multiple threads management and the event notification system .https://github.com/apache/tvm/pull/10234
- [x] Pipeline executor, pipeline execution,  data forwarding for internal binding data https://github.com/apache/tvm/pull/10543
- [x] Pipeline executor, pipeline execution,  runtime CPU affinity configuration and applying.https://github.com/apache/tvm/pull/10639
- [x] Pipeline executor, pipeline execution,  runtime asynchronous run,  and getting output.https://github.com/apache/tvm/pull/10723
- [x] Pipeline executor, pipeline execution,  data forwarding for "on the fly" input data.https://github.com/apache/tvm/pull/10990
- [x]  Refactor PipelineExecutor.py and Add cross compile support for pipeline executor https://github.com/apache/tvm/pull/11133
- [x] Add network split logic into unit test https://github.com/apache/tvm/pull/11334
- [x] Pipeline executor tutorial.https://github.com/apache/tvm/pull/11557
## [Enable CPU Affinity]
- [x] Binding the control flow/data flow thread of  backend runtime on a/a group of  CPU.https://github.com/apache/tvm/pull/9802

## PR is not in this solution scope but related, separate issue used to track.
|Compute graph splitting function|PR| Tracking Issue|
| :------------------------------------|:------------------------------------|:----|
|Splitting  compute  graph  into  a  list  of  subgraph  in  C++.|||

| Compute graph automatic splitting| PR| Tracking Issue|
|:------------------|:-------------------|:----|
|compute graph automatic splitting infrastructure|||
|compute graph auto splitting interface and example|||
|compute graph auto tune and graph splitting algorithm implementation|||

| non-DNN model function pipeline integration support| PR| Tracking Issue|
|:------------|:------------|:-------------|
|Add darknet operator  for yolov3 data preparation(pre-processing )|||
|Add darknet operator for  yolov3 detection result analysis(post processing)|||

**Comment by comaniac** [comment]
@huajsj please update this issue with a PR checklist. Please link all future PRs to this issue for better progress tracking.
You can refer to other RFC issues like #8473

**Comment by huajsj** [comment]
@comaniac , thanks for the follow up, just saw this comments,  already done.

**Comment by comaniac** [comment]
> @comaniac , thanks for the follow up, just saw this comments, already done.

Could you update the issue with a complete plan (e.g., milestones, expected PRs) instead of adding one line when filing a PR? Otherwise people won't have an idea about how many PRs you are going to send and what milestone you have achieved.

**Comment by huajsj** [comment]
@comaniac , sure, already add the future PR plan.

**Comment by huajsj** [comment]
@comaniac, I just updated this issue to move these planned PR not belong to this solution to  sperate tables to avoid confuse, please check.

**Comment by rebel-shshin** [comment]
@huajsj Thanks for the nice job.

**Comment by masahi** [comment]
At one point can we expect a non-trivial demo?

**Comment by huajsj** [comment]
thanks @masahi for the follow up, I am also looking forward a chance to do a demo after all patch upstream done.

**Comment by rebel-shshin** [comment]
> thanks @masahi for the follow up, I am also looking forward a chance to do a demo after all patch upstream done.

Hi @huajsj, do you have any plan to do a demo with compiling deep learning models such as [https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py](url)?

**Comment by huajsj** [comment]
> > thanks @masahi for the follow up, I am also looking forward a chance to do a demo after all patch upstream done.
> 
> Hi @huajsj, do you have any plan to do a demo with compiling deep learning models such as [TF model to relay]([https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py](https://github.com/apache/tvm/issues/url)](https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py%5D(https://github.com/apache/tvm/issues/url)) ?
> 
> And I think it would be helpful to the TVM users if you provide an example with BYOC also. Thank you very much :)

@rebel-shshin, thanks for the follow up, yes, a tutorial is a very good suggestion, actually we are working on the related document, I would add a tutorial task under this issue for tracking purpose.

**Comment by rebel-shshin** [comment]
> > > thanks @masahi for the follow up, I am also looking forward a chance to do a demo after all patch upstream done.
> > 
> > 
> > Hi @huajsj, do you have any plan to do a demo with compiling deep learning models such as [TF model to relay]([https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py](https://github.com/apache/tvm/issues/url)](https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py%5D(https://github.com/apache/tvm/issues/url)) ?
> > And I think it would be helpful to the TVM users if you provide an example with BYOC also. Thank you very much :)
> 
> @rebel-shshin, thanks for the follow up, yes, a tutorial is a very good suggestion, actually we are working on the related document, I would add a tutorial task under this issue for tracking purpose.

Thank you very much :)

**Comment by huajsj** [comment]
> > > > thanks @masahi for the follow up, I am also looking forward a chance to do a demo after all patch upstream done.
> > > 
> > > 
> > > Hi @huajsj, do you have any plan to do a demo with compiling deep learning models such as [TF model to relay]([https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py](https://github.com/apache/tvm/issues/url)](https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py%5D(https://github.com/apache/tvm/issues/url)) ?
> > > And I think it would be helpful to the TVM users if you provide an example with BYOC also. Thank you very much :)
> > 
> > 
> > @rebel-shshin, thanks for the follow up, yes, a tutorial is a very good suggestion, actually we are working on the related document, I would add a tutorial task under this issue for tracking purpose.
> 
> Thank you very much :)

Hi @rebel-shshin , tutorial already there, https://github.com/apache/tvm/pull/11557.

**Comment by huajsj** [comment]
all the task done, thanks @comaniac and @masahi for the kindly review, thanks @rebel-shshin for the follow up, close this issue now.

**Comment by rebel-shshin** [comment]
> > > > > thanks @masahi for the follow up, I am also looking forward a chance to do a demo after all patch upstream done.
> > > > 
> > > > 
> > > > Hi @huajsj, do you have any plan to do a demo with compiling deep learning models such as [TF model to relay]([https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py](https://github.com/apache/tvm/issues/url)](https://tvm.apache.org/docs/how_to/compile_models/from_tensorflow.html#sphx-glr-how-to-compile-models-from-tensorflow-py%5D(https://github.com/apache/tvm/issues/url)) ?
> > > > And I think it would be helpful to the TVM users if you provide an example with BYOC also. Thank you very much :)
> > > 
> > > 
> > > @rebel-shshin, thanks for the follow up, yes, a tutorial is a very good suggestion, actually we are working on the related document, I would add a tutorial task under this issue for tracking purpose.
> > 
> > 
> > Thank you very much :)
> 
> Hi @rebel-shshin , tutorial already there, #11557.

Thank you very much : )
