### ISSUE TITLE
[Tracking issue] Quantized TFLite operators

### ISSUE THREAD

**Issue by leandron** [apache/tvm#9187]
As part of https://github.com/apache/tvm/pull/9165, we recently enabled support for quantized operators in the TFLite frontend "unary element-wise" function, that does generic support for a few operators.

That opens the door for more operators to be supported easily, just pending the addition of tests and logically _unlocking_ the conditional block that is keeping the quantised version of the operator to be unsupported. See the example as implemented in  https://github.com/apache/tvm/pull/9165.

This is a tracking issue for new unary element-wise operators to be supported:

- [x] `GREATER` #12754 @dchauhan-arm 
- [x] `EQUAL` #11520 @dchauhan-arm 
- [x] `CEIL` #10566 by @leeexyz 
- [x] `ROUND` #10566 by @leeexyz 
- [x] `FLOOR` #10566 by @leeexyz 
- [x] `EXP` #10566 by @leeexyz 
- [x] `LOG` #10566 by @leeexyz 
- [x] `SIN` #9478 by @onkar-sima-ai
- [x] `TAN` #10566 by @leeexyz 
- [x] `COS` #10566 by @leeexyz 
- [x] `SQRT` #9258 by @elinx
- [x] `RSQRT` #9165 by @ophirfrish
- [x] `NEG` #9404 by @ophirfrish 

For each operator above, there are actions to be taken:
1. Remove the conditional block `if self.is_quantized(op): ...`
2. Implement unit tests
3. ask any [committer](https://github.com/apache/tvm/blob/main/CONTRIBUTORS.md) in the project to update this issue, reflecting the PR to support the operators on the list above

#9165 can be used as an example.

Resources:
* TFlite frontend: https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/tflite.py

**Comment by onkar-sima-ai** [comment]
Hi @leandron can you please update this issue and if possible review the PR for qunatized SIN operator?
I have followed the instruction in this issue to write the test cases.

Please let me know if I need to do any changes.
Thanks for posting, Happy to contribute.

**Comment by leandron** [comment]
> Hi @leandron can you please update this issue and if possible review the PR for qunatized SIN operator? I have followed the instruction in this issue to write the test cases.
> 
> Please let me know if I need to do any changes. Thanks for posting, Happy to contribute.

Done! thanks @onkar-sima-ai

**Comment by psigillito** [comment]
Hi @leandron I am interested in getting to know the source code better. Is the list of operators up to date? I might try implementing the GREATER operator using #9165 as a template. Thanks!

**Comment by leandron** [comment]
> Hi @leandron I am interested in getting to know the source code better. Is the list of operators up to date? I might try implementing the GREATER operator using https://github.com/apache/tvm/pull/9165 as a template. Thanks!

Sorry I missed your message. I've just updated the list of operator.
To your question: yes, you can use #9165 as a template.

**Comment by lhutton1** [comment]
Thanks @dchauhan-arm @leeexyz @onkar-sima-ai @elinx @ophirfrish for the contributions towards this effort! Closing as it is now complete.
