### ISSUE TITLE
[Torch, CI] Upgrade to PyTorch 1.10

### ISSUE THREAD

**Issue by masahi** [apache/tvm#9349]
PyTorch 1.10 has just been released. We are now at PT 1.7 which we upgraded to one year ago. I think it is a good time for another update. 
https://pytorch.org/blog/pytorch-1.10-released/

Recently I've been sensing growing interest in more tight integration with PyTorch, for example using TVM as a backend in a PyTorch-based application (https://github.com/apache/tvm/pull/8777) or using TVM for training acceleration. I'm looking forward to seeing more development in this space, in addition to continuing to support the traditional usage of TVM as a e2e inference solution for PT models. From these point of view, I believe having our PT support up-to-date and actively maintained is increasingly important.   

- [x] Figure out what's broken, any API change
- [x] Investigate the symbol crash issue https://github.com/apache/tvm/issues/9362
- [x] Send out necessary fix
- [x] Upgrade the CI GPU image

**Comment by masahi** [comment]
Upgrade to PT v1.10 is now complete.
