### ISSUE TITLE
[Tracking Issue] Arm Ethos-N updates

### ISSUE THREAD

**Issue by Leo-arm** [apache/tvm#9351]
### This issue is to track progress for planned updates for the Arm Ethos-N.
- [x] P1. Alignment of IsSupported calls and compiler for different variants (https://github.com/apache/tvm/pull/9160). This paves the way for P2.
- [x] P2. Support for variants. This allows code generation for a number of Ethos-N78 hardware configurations with default memories (https://github.com/apache/tvm/pull/9386).
- [ ] P3. Remove some code duplication, fix double specification of target variant, consistent naming of target and product names, general cleanup
- [x] P4. Support for configurable sram memories. This extends P2 above to also specify the amount of on-board memory. Update: no change required. A future update will improve the error handling when memory is specified incorrectly.

**Comment by masahi** [comment]
I assume it has been completed.
