### ISSUE TITLE
[Tracking Issue] Arm(R) Ethos(TM)-U NPU operator support

### ISSUE THREAD

**Issue by ekalda** [apache/tvm#9410]
### This issue is to track progress for Arm(R) Ethos(TM)-U NPU operator support
- [x] P1. POOLING operators (https://github.com/apache/tvm/pull/9384)
- [x] P2. Identity operator with STRIDED SLICE and RESHAPE operators (https://github.com/apache/tvm/pull/9457)
- [x] P3. Replacing Conv2d tests and deprecating Relay IR builder (https://github.com/apache/tvm/pull/9508)
- [x] P4. 4D Binary elementwise operators (https://github.com/apache/tvm/pull/9442)
    - [x] P5. Support non-4D Binary elementwise operations (https://github.com/apache/tvm/pull/9521)
- [x] P6. Unary elementwise operators
    - [x] P6a. ABS (https://github.com/apache/tvm/pull/9530)
    - [x] P6b. CLZ (https://github.com/apache/tvm/pull/9577#issuecomment-979121281)
- [x] P7. CONCATENATE (https://github.com/apache/tvm/pull/9589)
- [x] P8. FULLY CONNECTED (https://github.com/apache/tvm/pull/10345)
- [x] P9. SPLIT and SPLIT_V (https://github.com/apache/tvm/pull/9621)
- [x] P10. Lookup table implementation with TANH (https://github.com/apache/tvm/pull/9547)
    - [x] P10a. SIGMOID (https://github.com/apache/tvm/pull/9627)
- [x] P11. NHWC -> NHCWB16 layout transformation pass (https://github.com/apache/tvm/pull/9561)
- [x] P12. MEAN (https://github.com/apache/tvm/pull/9576)

**Comment by ekalda** [comment]
All the operators that were part of this tracking issue are merged now!
