### ISSUE TITLE
[Tracking Issue] Continued Arm(R) Ethos(TM)-U NPU operator support

### ISSUE THREAD

**Issue by lhutton1** [apache/tvm#9961]
This issue is to track progress for Arm(R) Ethos(TM)-U NPU operator support. It follows on from #9410 which contains previously submitted and merged PR's for operator support.

- [x] FULLY CONNECTED (#10345)
- [ ] HARD SWISH
- [x] SLICE (completed in #9410)
- [x] RESIZE BILINEAR (#9841)
- [x] PACK (#9960)
- [x] UNPACK (#9960)
- [x] LRELU (int8 variant) (#10127)
- [x] QUANTIZE (requantize) (#9910)
- [x] TRANSPOSE CONVOLUTION (2x2 strides only) (#9855)
- [x] Removal of redundant identity operators (#10254)
- [ ] Addressing comments on testing for all operators
